apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}      
  name: {{ include "bitbucket.fullname" . }}
  labels:
    app: {{ include "bitbucket.name" . }}
    chart: {{ include "bitbucket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "bitbucket.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "bitbucket.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: bitbucket-vol
          persistentVolumeClaim:
            claimName: {{ default (include "bitbucket.fullname" .) }}-data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: '7990'
            - name: SERVER_SCHEME
              value: https
            - name: SERVER_SECURE
              value: 'true'
            - name: SERVER_PROXY_PORT
              value: '443'
            - name: SERVER_PROXY_NAME
              value: '{{ .Values.proxyName }}'
          volumeMounts:
             - name: bitbucket-vol
               mountPath: /var/atlassian/application-data/bitbucket
          ports:
            - name: bitbucket
              containerPort: 7990
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
