apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "bitbucket.fullname" . }}
  labels:
    app: {{ include "bitbucket.name" . }}
    chart: {{ include "bitbucket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  to:
    kind: Service
    name: {{ include "bitbucket.fullname" . }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: 7990  