apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "bitbucket.fullname" . }}
  labels:
    app: {{ include "bitbucket.name" . }}
    chart: {{ include "bitbucket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7990
      protocol: TCP
      name: http
  selector:
    app: {{ include "bitbucket.name" . }}
    release: {{ .Release.Name }}
